#!/bin/bash

# SnailyCAD Database Import Script - AUTO-HEALING VERSION
# Automatically fixes authentication and permission issues

set -uo pipefail

# Configuration
LOG_FILE="/tmp/snaily_import_$(date +%Y%m%d_%H%M%S).log"
BACKUP_SEARCH_DIR="/home"
TEMP_DIR="/tmp/snaily_import_temp_$$"
RESULT_FILE="/tmp/snaily_result_$$"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

# Database config
DB_NAME=""
DB_USER=""
DB_PASSWORD=""
DB_HOST=""
DB_PORT=""
ENV_FILE_PATH=""

# Logging functions
log() {
    echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

log_heal() {
    echo -e "${MAGENTA}[AUTO-HEAL]${NC} $1" | tee -a "$LOG_FILE"
}

# Cleanup function
cleanup() {
    rm -f "$RESULT_FILE" 2>/dev/null || true
}

trap cleanup EXIT

# Extract database credentials from .env file
extract_db_credentials() {
    local env_file="$1"
    
    log "Extracting database credentials from .env file..."
    
    if [[ ! -f "$env_file" ]]; then
        log_error "Environment file not found: $env_file"
        return 1
    fi
    
    ENV_FILE_PATH="$env_file"
    
    # Extract credentials with better parsing
    DB_HOST=$(grep -E '^DATABASE_HOST=' "$env_file" 2>/dev/null | cut -d '=' -f2- | sed 's/^["'\'']*//;s/["'\'']*$//' | tr -d '[:space:]' || echo "")
    DB_PORT=$(grep -E '^DATABASE_PORT=' "$env_file" 2>/dev/null | cut -d '=' -f2- | sed 's/^["'\'']*//;s/["'\'']*$//' | tr -d '[:space:]' || echo "")
    DB_NAME=$(grep -E '^DATABASE_NAME=' "$env_file" 2>/dev/null | cut -d '=' -f2- | sed 's/^["'\'']*//;s/["'\'']*$//' | tr -d '[:space:]' || echo "")
    DB_USER=$(grep -E '^DATABASE_USER=' "$env_file" 2>/dev/null | cut -d '=' -f2- | sed 's/^["'\'']*//;s/["'\'']*$//' | tr -d '[:space:]' || echo "")
    DB_PASSWORD=$(grep -E '^DATABASE_PASSWORD=' "$env_file" 2>/dev/null | cut -d '=' -f2- | sed 's/^["'\'']*//;s/["'\'']*$//' || echo "")
    
    # Set defaults if empty
    DB_HOST=${DB_HOST:-"localhost"}
    DB_PORT=${DB_PORT:-"5432"}
    DB_NAME=${DB_NAME:-"snailycad"}
    DB_USER=${DB_USER:-"snailycad"}
    DB_PASSWORD=${DB_PASSWORD:-"password"}
    
    log_success "Database credentials extracted:"
    log_info "  Host: $DB_HOST"
    log_info "  Port: $DB_PORT"
    log_info "  Database: $DB_NAME"
    log_info "  User: $DB_USER"
    log_info "  Password: [${#DB_PASSWORD} characters]"
    
    return 0
}

# Advanced PostgreSQL authentication setup with healing
setup_postgresql_auth_healing() {
    log_heal "=== HEALING POSTGRESQL AUTHENTICATION ==="
    
    local pg_hba_file=""
    local pg_version_dir=""
    
    # Find PostgreSQL config
    for version_dir in /etc/postgresql/*/main; do
        if [[ -f "$version_dir/pg_hba.conf" ]]; then
            pg_hba_file="$version_dir/pg_hba.conf"
            pg_version_dir="$version_dir"
            break
        fi
    done
    
    if [[ -z "$pg_hba_file" ]]; then
        log_error "PostgreSQL config not found"
        return 1
    fi
    
    log_info "Found config: $pg_hba_file"
    
    # Backup original
    if [[ ! -f "$pg_hba_file.backup_$(date +%Y%m%d)" ]]; then
        cp "$pg_hba_file" "$pg_hba_file.backup_$(date +%Y%m%d)" 2>/dev/null || true
        log_success "Config backed up"
    fi
    
    # Create optimized pg_hba.conf
    log_heal "Rewriting pg_hba.conf for proper authentication..."
    
    cat > "$pg_hba_file" <<EOF
# PostgreSQL Client Authentication Configuration File
# ===================================================
# Auto-generated by SnailyCAD import script
# Backup: $pg_hba_file.backup_$(date +%Y%m%d)

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             postgres                                trust
local   all             all                                     md5

# IPv4 local connections:
host    all             postgres        127.0.0.1/32            trust
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5

# IPv6 local connections:
host    all             postgres        ::1/128                 trust
host    all             all             ::1/128                 md5
EOF
    
    log_success "pg_hba.conf updated"
    
    # Also update postgresql.conf for network listening
    local pg_conf="$pg_version_dir/postgresql.conf"
    if [[ -f "$pg_conf" ]]; then
        if ! grep -q "^listen_addresses.*=.*'\*'" "$pg_conf" 2>/dev/null; then
            log_heal "Enabling network listening..."
            sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$pg_conf" 2>/dev/null || true
            sed -i "s/listen_addresses = 'localhost'/listen_addresses = '*'/" "$pg_conf" 2>/dev/null || true
        fi
    fi
    
    # Restart PostgreSQL
    log_heal "Restarting PostgreSQL..."
    systemctl restart postgresql 2>/dev/null || service postgresql restart 2>/dev/null || true
    sleep 5
    
    if systemctl is-active --quiet postgresql 2>/dev/null; then
        log_success "PostgreSQL restarted successfully"
    else
        log_warning "PostgreSQL status unknown, continuing..."
    fi
    
    return 0
}

# Check dependencies
check_dependencies() {
    log "Checking dependencies..."
    
    local missing_deps=()
    for cmd in psql createdb dropdb pg_restore tar gunzip; do
        if ! command -v "$cmd" &>/dev/null; then
            missing_deps+=("$cmd")
        fi
    done
    
    if [[ ${#missing_deps[@]} -gt 0 ]]; then
        log_warning "Missing: ${missing_deps[*]}"
        if command -v apt-get &>/dev/null; then
            log "Installing packages..."
            apt-get update -qq 2>/dev/null || true
            apt-get install -y postgresql postgresql-contrib tar gzip 2>/dev/null || true
        fi
    fi
    
    log_success "All dependencies available"
    
    if systemctl is-active --quiet postgresql 2>/dev/null; then
        log_success "PostgreSQL is running"
    else
        systemctl start postgresql 2>/dev/null || true
        sleep 2
    fi
    
    return 0
}

# Completely reset and recreate database user
reset_database_user() {
    log_heal "=== RESETTING DATABASE USER ==="
    
    # Terminate all connections from this user
    log_heal "Terminating existing connections..."
    su - postgres -c "psql -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='$DB_USER';\"" &>/dev/null || true
    sleep 2
    
    # Remove user completely
    log_heal "Removing existing user..."
    su - postgres -c "psql -c \"DROP OWNED BY \\\"$DB_USER\\\" CASCADE;\"" &>/dev/null || true
    su - postgres -c "psql -c \"DROP USER IF EXISTS \\\"$DB_USER\\\";\"" &>/dev/null || true
    sleep 1
    
    # Create fresh user with all privileges
    log_heal "Creating fresh user with full privileges..."
    local safe_password="${DB_PASSWORD//\'/\'\'}"
    
    su - postgres -c "psql" <<EOF 2>&1 | tee -a "$LOG_FILE"
CREATE USER "$DB_USER" WITH 
    PASSWORD '$safe_password'
    SUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    LOGIN
    REPLICATION
    BYPASSRLS;
EOF
    
    if su - postgres -c "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'\"" 2>/dev/null | grep -q "1"; then
        log_success "User recreated successfully"
    else
        log_error "Failed to create user"
        return 1
    fi
    
    return 0
}

# Setup database with complete reset
setup_database_healing() {
    log_heal "=== HEALING DATABASE SETUP ==="
    
    # Drop database if exists
    log_heal "Dropping existing database..."
    su - postgres -c "psql -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='$DB_NAME';\"" &>/dev/null || true
    sleep 2
    su - postgres -c "dropdb \"$DB_NAME\" --if-exists" 2>&1 | tee -a "$LOG_FILE" || true
    sleep 1
    
    # Create fresh database
    log_heal "Creating fresh database..."
    if su - postgres -c "createdb -O \"$DB_USER\" \"$DB_NAME\"" 2>&1 | tee -a "$LOG_FILE"; then
        log_success "Database created"
    else
        log_error "Failed to create database"
        return 1
    fi
    
    # Grant all privileges
    log_heal "Granting privileges..."
    su - postgres -c "psql" <<EOF 2>&1 | tee -a "$LOG_FILE"
GRANT ALL PRIVILEGES ON DATABASE "$DB_NAME" TO "$DB_USER";
ALTER DATABASE "$DB_NAME" OWNER TO "$DB_USER";
\c "$DB_NAME"
GRANT ALL ON SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$DB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$DB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$DB_USER";
EOF
    
    log_success "Database setup complete"
    return 0
}

# Test database authentication
test_authentication() {
    log "Testing database authentication..."
    
    export PGPASSWORD="$DB_PASSWORD"
    
    local test_output
    test_output=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 'CONNECTION_OK' as status;" 2>&1)
    
    if echo "$test_output" | grep -q "CONNECTION_OK"; then
        log_success "✓ Authentication SUCCESSFUL"
        return 0
    else
        log_error "✗ Authentication FAILED"
        log_error "Output: $test_output"
        return 1
    fi
}

# Create/update .pgpass file for passwordless authentication
create_pgpass() {
    log_heal "Creating .pgpass file for user: $DB_USER"
    
    local pgpass_file="/home/$DB_USER/.pgpass"
    
    # Create .pgpass entry
    echo "$DB_HOST:$DB_PORT:$DB_NAME:$DB_USER:$DB_PASSWORD" > "$pgpass_file"
    echo "$DB_HOST:$DB_PORT:*:$DB_USER:$DB_PASSWORD" >> "$pgpass_file"
    echo "localhost:$DB_PORT:$DB_NAME:$DB_USER:$DB_PASSWORD" >> "$pgpass_file"
    echo "localhost:$DB_PORT:*:$DB_USER:$DB_PASSWORD" >> "$pgpass_file"
    
    chown "$DB_USER:$DB_USER" "$pgpass_file" 2>/dev/null || true
    chmod 600 "$pgpass_file" 2>/dev/null || true
    
    log_success ".pgpass created at: $pgpass_file"
    
    # Also create for root
    local root_pgpass="/root/.pgpass"
    cp "$pgpass_file" "$root_pgpass" 2>/dev/null || true
    chmod 600 "$root_pgpass" 2>/dev/null || true
    
    return 0
}

# Find backup archive
find_backup_archive() {
    local backup_files=()
    
    while IFS= read -r file; do
        [[ -f "$file" ]] && backup_files+=("$file")
    done < <(find "$BACKUP_SEARCH_DIR" -maxdepth 3 -type f -name "*.tar.gz" 2>/dev/null)
    
    if [[ ${#backup_files[@]} -eq 0 ]]; then
        return 1
    fi
    
    local latest_backup="" latest_time=0
    for file in "${backup_files[@]}"; do
        local file_time
        file_time=$(stat -c %Y "$file" 2>/dev/null || echo "0")
        if [[ "$file_time" -gt "$latest_time" ]]; then
            latest_time="$file_time"
            latest_backup="$file"
        fi
    done
    
    if [[ -n "$latest_backup" && -f "$latest_backup" ]]; then
        echo "$latest_backup" > "$RESULT_FILE"
        return 0
    fi
    
    return 1
}

# Extract backup archive
extract_backup_archive() {
    local archive_path="$1"
    
    log "Extracting: $(basename "$archive_path")"
    
    mkdir -p "$TEMP_DIR" 2>/dev/null || {
        log_error "Failed to create temp directory"
        return 1
    }
    
    if tar -xzf "$archive_path" -C "$TEMP_DIR" 2>>"$LOG_FILE"; then
        local count
        count=$(find "$TEMP_DIR" -type f 2>/dev/null | wc -l)
        log_success "Extracted $count files to: $TEMP_DIR"
        return 0
    else
        log_error "Extraction failed"
        return 1
    fi
}

# Locate backup files
locate_backup_files() {
    local env_file db_dump
    
    env_file=$(find "$TEMP_DIR" -type f \( -name "env_backup_*" -o -name ".env" -o -name "*.env" \) 2>/dev/null | head -n1)
    [[ -z "$env_file" || ! -f "$env_file" ]] && return 1
    
    db_dump=$(find "$TEMP_DIR" -type f \( -name "db_backup_*" -o -name "*.sql" -o -name "*.dump" \) 2>/dev/null | head -n1)
    [[ -z "$db_dump" || ! -f "$db_dump" ]] && return 1
    
    echo "$env_file|$db_dump" > "$RESULT_FILE"
    return 0
}

# Import database with healing
import_database_healing() {
    local db_dump="$1"
    
    log_heal "=== IMPORTING DATABASE WITH AUTO-HEALING ==="
    log_info "Dump file: $db_dump"
    log_info "Size: $(du -h "$db_dump" 2>/dev/null | cut -f1 || echo "unknown")"
    
    export PGPASSWORD="$DB_PASSWORD"
    
    # Method 1: Direct import as database user
    log_heal "Attempt 1: Direct import as $DB_USER"
    if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f "$db_dump" 2>&1 | tee -a "$LOG_FILE"; then
        log_success "Import successful (Method 1)"
        return 0
    fi
    
    # Method 2: Import as postgres, then reassign
    log_heal "Attempt 2: Import as postgres user"
    if su - postgres -c "psql -d \"$DB_NAME\" -f \"$db_dump\"" 2>&1 | tee -a "$LOG_FILE"; then
        log_success "Import successful (Method 2)"
        
        # Reassign ownership
        log_heal "Reassigning ownership to $DB_USER..."
        su - postgres -c "psql -d \"$DB_NAME\"" <<EOF 2>&1 | tee -a "$LOG_FILE"
REASSIGN OWNED BY postgres TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "$DB_USER";
EOF
        return 0
    fi
    
    log_error "All import methods failed"
    return 1
}

# Update .env file with correct credentials
update_env_file() {
    local target_env="$1"
    
    log_heal "Updating .env file with verified credentials..."
    
    # Backup original
    if [[ -f "$target_env" ]]; then
        cp "$target_env" "$target_env.backup_$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
    fi
    
    # Update or add database credentials
    sed -i "s|^DATABASE_HOST=.*|DATABASE_HOST=\"$DB_HOST\"|" "$target_env" 2>/dev/null || \
        echo "DATABASE_HOST=\"$DB_HOST\"" >> "$target_env"
    
    sed -i "s|^DATABASE_PORT=.*|DATABASE_PORT=\"$DB_PORT\"|" "$target_env" 2>/dev/null || \
        echo "DATABASE_PORT=\"$DB_PORT\"" >> "$target_env"
    
    sed -i "s|^DATABASE_NAME=.*|DATABASE_NAME=\"$DB_NAME\"|" "$target_env" 2>/dev/null || \
        echo "DATABASE_NAME=\"$DB_NAME\"" >> "$target_env"
    
    sed -i "s|^DATABASE_USER=.*|DATABASE_USER=\"$DB_USER\"|" "$target_env" 2>/dev/null || \
        echo "DATABASE_USER=\"$DB_USER\"" >> "$target_env"
    
    sed -i "s|^DATABASE_PASSWORD=.*|DATABASE_PASSWORD=\"$DB_PASSWORD\"|" "$target_env" 2>/dev/null || \
        echo "DATABASE_PASSWORD=\"$DB_PASSWORD\"" >> "$target_env"
    
    log_success ".env file updated with working credentials"
    return 0
}

# Restore environment file with healing
restore_env_file_healing() {
    local env_file="$1"
    
    log_heal "=== HEALING ENVIRONMENT FILE ==="
    
    local target_dir="/home/$DB_USER"
    local target_env="$target_dir/.env"
    
    mkdir -p "$target_dir" 2>/dev/null || true
    
    # Copy original .env
    if cp "$env_file" "$target_env" 2>/dev/null; then
        log_success "Environment file copied"
    else
        log_error "Failed to copy .env"
        return 1
    fi
    
    # Update with verified credentials
    update_env_file "$target_env"
    
    # Set permissions
    chown -R "$DB_USER:$DB_USER" "$target_dir" 2>/dev/null || true
    chmod 600 "$target_env" 2>/dev/null || true
    
    log_success "Environment file restored to: $target_env"
    
    # Also check for SnailyCAD app directory
    if [[ -d "/home/snaily-cadv4" ]]; then
        log_heal "Found SnailyCAD app directory, updating there too..."
        cp "$target_env" "/home/snaily-cadv4/.env" 2>/dev/null || true
        chown "$DB_USER:$DB_USER" "/home/snaily-cadv4/.env" 2>/dev/null || true
        chmod 600 "/home/snaily-cadv4/.env" 2>/dev/null || true
        log_success "Updated /home/snaily-cadv4/.env"
    fi
    
    return 0
}

# Verify import comprehensively
verify_import_comprehensive() {
    log "=== COMPREHENSIVE VERIFICATION ==="
    
    export PGPASSWORD="$DB_PASSWORD"
    
    # Test 1: Connection
    log "Test 1: Database connection..."
    if test_authentication; then
        log_success "Connection: PASS"
    else
        log_error "Connection: FAIL"
        return 1
    fi
    
    # Test 2: Table count
    log "Test 2: Table count..."
    local table_count
    table_count=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public';" 2>/dev/null || echo "0")
    
    if [[ "$table_count" -gt 0 ]]; then
        log_success "Tables: $table_count found"
    else
        log_error "No tables found"
        return 1
    fi
    
    # Test 3: Sample tables
    log "Test 3: Sample tables..."
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename LIMIT 10;" 2>/dev/null | while read -r table; do
        [[ -n "$table" ]] && log_info "  ✓ $table"
    done
    
    # Test 4: Permissions
    log "Test 4: User permissions..."
    local perms
    perms=$(su - postgres -c "psql -tAc \"SELECT string_agg(rolname, ', ') FROM pg_roles WHERE rolsuper = true;\"" 2>/dev/null || echo "")
    if echo "$perms" | grep -q "$DB_USER"; then
        log_success "User has SUPERUSER privileges"
    else
        log_warning "User might not have full privileges"
    fi
    
    # Test 5: .env file
    log "Test 5: Environment files..."
    for env_path in "/home/$DB_USER/.env" "/home/snaily-cadv4/.env"; do
        if [[ -f "$env_path" && -s "$env_path" ]]; then
            log_success "✓ $env_path"
        fi
    done
    
    log_success "All verification tests completed"
    return 0
}

# Main healing function
perform_complete_healing() {
    log_heal "======================================================="
    log_heal "   PERFORMING COMPLETE AUTO-HEALING"
    log_heal "======================================================="
    
    # Step 1: Fix PostgreSQL authentication
    if ! setup_postgresql_auth_healing; then
        log_error "Failed to heal PostgreSQL authentication"
        return 1
    fi
    
    # Step 2: Reset database user
    if ! reset_database_user; then
        log_error "Failed to reset database user"
        return 1
    fi
    
    # Step 3: Create .pgpass
    create_pgpass
    
    # Step 4: Setup database
    if ! setup_database_healing; then
        log_error "Failed to setup database"
        return 1
    fi
    
    # Step 5: Test authentication
    if ! test_authentication; then
        log_error "Authentication still failing after healing"
        return 1
    fi
    
    log_success "Auto-healing completed successfully"
    return 0
}

# Main function
main() {
    echo ""
    log "==================================================================="
    log "    SnailyCAD Database Import - AUTO-HEALING VERSION"
    log "==================================================================="
    log "This script will automatically fix authentication issues"
    log "Log: $LOG_FILE"
    echo ""
    
    check_dependencies
    
    # Find backup
    log "Searching for backup in: $BACKUP_SEARCH_DIR"
    if find_backup_archive; then
        local backup_archive
        backup_archive=$(cat "$RESULT_FILE")
        log_success "Found: $backup_archive"
    else
        log_error "No backup archive found"
        exit 1
    fi
    
    # Extract
    if ! extract_backup_archive "$backup_archive"; then
        exit 1
    fi
    
    # Locate files
    if locate_backup_files; then
        local env_file db_dump
        IFS='|' read -r env_file db_dump < "$RESULT_FILE"
        log_success "ENV: $(basename "$env_file")"
        log_success "DB: $(basename "$db_dump")"
    else
        log_error "Could not find backup files"
        exit 1
    fi
    
    # Extract credentials
    if ! extract_db_credentials "$env_file"; then
        exit 1
    fi
    
    # Perform complete healing
    if ! perform_complete_healing; then
        log_error "Healing failed"
        exit 1
    fi
    
    # Import database
    if ! import_database_healing "$db_dump"; then
        log_error "Import failed"
        exit 1
    fi
    
    # Restore .env with healing
    if ! restore_env_file_healing "$env_file"; then
        log_warning "Environment file restore had issues"
    fi
    
    # Comprehensive verification
    if ! verify_import_comprehensive; then
        log_warning "Some verification tests failed"
    fi
    
    # Final success message
    echo ""
    log "==================================================================="
    log_success "    ✓ IMPORT AND HEALING COMPLETED SUCCESSFULLY!"
    log "==================================================================="
    echo ""
    log "Database Configuration:"
    log "  Database: $DB_NAME"
    log "  Host: $DB_HOST:$DB_PORT"
    log "  User: $DB_USER"
    log "  Password: [verified and working]"
    echo ""
    log "Configuration Files:"
    log "  Primary: /home/$DB_USER/.env"
    [[ -f "/home/snaily-cadv4/.env" ]] && log "  App: /home/snaily-cadv4/.env"
    echo ""
    log "Test Connection:"
    log "  PGPASSWORD='$DB_PASSWORD' psql -h $DB_HOST -U $DB_USER -d $DB_NAME"
    echo ""
    log "Log File: $LOG_FILE"
    log "==================================================================="
    echo ""
    
    log_success "You can now start SnailyCAD - authentication should work!"
    echo ""
}

main "$@"
